### PR TITLE
GitHub action publish nuget

### PR DESCRIPTION
**Pull request by Miiraak**
## Purpose :
- [ GitHub Action #7 ](https://github.com/m-henderson/ProxySharp/issues/7)

## Details :
Enhanced the ProxySharp.csproj file with additional properties:
- Title, Authors, Description, PackageProjectUrl, PackageIcon,
  PackageReadmeFile, RepositoryUrl, PackageTags, and Version.
- Included ProxySharpIcon.jpeg and README.md in the packaging.

- Change name `dotnet.yml` to `Tests&PublishToNuget.yml` 
- Improve and rework `Tests&PublishToNuget.yml` for test and publish to nuget.org 

These changes improve project documentation and distribution.

## Notes :
@m-henderson
The PR will not work until changes made. (precisely publish is Skipped)

- Create an API key on nuget.org
   - Copy Nuget API Key
- On github repository `ProxySharp`
   - Settings > Secrets and variables > New Respository secret
   - Give a name
   - Undere Secret copy the Nuget API key
- Then you need to modify `Tests&PublishToNuget.yml`  at line 105
```yml
dotnet nuget push $file --api-key "${{ secrets.}}" --source https://api.nuget.org/v3/index.json
```
- Change `secret.` by `secret.NameOfSecret`

Then i think the action will be ready.

### CODE REVIEW

**Comment by m-henderson** [comment]
@Miiraak Awesome Pull Request. You left great notes and explained everything in detail. Im working on the Nuget stuff now.

**Comment by Miiraak** [comment]
Glad you liked it !
Thanks, i trying my best 👼🏼 

Would you do the conflicts resolve or i take a look ?

**Comment by m-henderson** [comment]
> @m-henderson Glad you liked it ! Thanks, i trying my best 👼🏼
> 
> Would you do the conflicts resolve or i take a look ?

You can do it if you would like. I added the following secret to the repo: NUGET_API_KEY

**Comment by m-henderson** [comment]
@Miiraak is this one good to merge?

**Comment by Miiraak** [comment]
@m-henderson yeah it seem okay for me

**Pull request merged**
